name: macOS Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build macOS Project
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: NotchDrop.xcodeproj
          scheme: NotchDrop
          destination: platform=macOS
          action: build
