name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Build NotchDrop
        uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: NotchDrop.xcodeproj
          scheme: NotchDrop
          destination: platform=macOS
          action: Release
