name: macOS Swift Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build macOS Project
    runs-on: macos-latest  # 必须使用 macOS 运行器

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build via xcodebuild
        run: |
          xcodebuild \
            -scheme "NotchDrop" \  # 替换为实际 Scheme 名称
            -destination "platform=macOS" \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            clean build
